//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string SecQuestion { get; set; }
        public string SecAnswer { get; set; }
        public string PrevOrder { get; set; }
        public MemeberPrivilege UserType { get; set; }
    }
}
